### ISSUE TITLE
How do I actually view the document?

### ISSUE THREAD

**Issue by RakibRyan** [phnix-dev/markdown-book#1]
![Screenshot (61)](https://github.com/user-attachments/assets/5f881e49-45c3-4db8-ba9e-73a46bc3e90f)
everytime I press a file it just takes me to scripts and the docs only show this

**Comment by phnix-dev** [comment]
Hello, It is hard to help you without much information about what you have done.
If you clone the repository and move the `docs` folder to your project, and set the `Project Settings > Addons > Markdown Book > Docs Folder` to `res://docs`, does that work?
If so, you can use the files in the `docs` folder as a starting point. (Look for a [SUMMARY.md](https://rust-lang.github.io/mdBook/guide/creating.html#summarymd) file if your project does not have one.)
